# api = localhost:8090
# usermanage = lcoalhost:5000

# GET
# User
### GET User Info
GET http://localhost:8090/api/users/1/info

### GET Cart For User
GET http://localhost:8090/api/users/2/cart/2

### GET Purchase History For User
GET http://localhost:8090/api/users/2/purchase%20history

### GET Payment Methods For User
GET http://localhost:8090/api/users/3/payment%20methods

# Product
### GET Products For Type
GET http://localhost:8090/api/types/1/products

### GET Items For Product
GET http://localhost:8090/api/products/1/items

### GET Photos For Item
GET http://localhost:8090/api/items/1/photos

# POST
# Login/Register
### CHECK Login Info
POST http://localhost:5000/usermanage/login
Content-Type: application/json

{
  "username": "sara",
  "password": "sarapassword"
}

### CHECK User Existence
POST http://localhost:5000/usermanage/register/check
Content-Type: application/json

{ 
  "username": "sara", 
  "email": "asdf@gmail.com"
}

### REGISTER New User
POST http://localhost:5000/usermanage/register
Content-Type: application/json

{
  "username": "david",
  "password": "dabid",
  "email": "david@hotmail",
  "phoneNumber": "052-783-0987",
  "address": "jerudalem, har hotzvim, 346",
  "permission": "customer"
}

# User
### ADD Payment Info
POST http://localhost:8090/api/users/3/pay
Content-Type: application/json

{
  "creditNum": "1234567891234567",
  "cvv": "123",
  "expDate": "2026-03-00"
}

# Product
### POST New Product
POST http://localhost:8090/api/products
Content-Type: application/json

{
  "productName": "airpods xp4567",
  "description": "big headphones soundproof",
  "typeId": "1",
  "cost": "600",
  "brand": "JBL"
}

### POST New Item
POST http://localhost:8090/api/products/1
Content-Type: application/json

{
  "color": "green",
  "amount": "3"
}

# Orders
### POST New Order
POST http://localhost:8090/api/orders/neworder/4
Content-Type: application/json

### ADD Item To Order
POST http://localhost:8090/api/orders/4/items
Content-Type: application/json

{
  "itemId": "1",
  "amount": "2"
}

### ADD Photo To Product
POST http://localhost:8090/api/items/:itemId/photos
Content-Type: image/jpeg, image/png

# PUT
# User
### CHANGE Active Payment
PUT http://localhost:8090/api/users/:userId/activepay
Content-Type: application/json

"paymentInfoId"

# Product
# EDIT Item
# EDIT Product

# Orders
### PUT Fulfill Order
PUT http://localhost:8090/api/orders/2
Content-Type: application/json

{
  "totalCost": 700,
  "paymentInfoId": 1
}

