# api = localhost:8080
# usermanage = lcoalhost:5000

# GET
# User
# GET User Info
GET http://localhost:8080/api/users/:userId/info

# GET Cart For User
GET http://localhost:8080/api/users/:userId/cart/:cartId

# GET Purchase History For User
GET http://localhost:8080/api/users/:userId/purchase+history

# GET Payment Methods For User
GET http://localhost:8080/api/users/:userId/payment+methods

# Product
# GET Products For Type
GET http://localhost:8080/api/types/:typeId/products

# GET Items For Product
GET http://localhost:8080/api/products/:productId/items

# GET Photos For Item
GET http://localhost:8080/api/items/itemId/photos

# POST
# Login/Register
# CHECK Login Info
POST http://localhost:5000/usermanage/login
Content-Type: application/json

{
  "username": "sara",
  "password": "sarapassword"
}

# CHECK User Existence
POST http://localhost:5000/usermanage/register/check
Content-Type: application/json

{ 
  "username": "sarahh", 
  "password": "saramail@gmail.commm"
}

# REGISTER New User
POST http://localhost:5000/usermanage/register
Content-Type: application/json

{
  "username": "david",
  "password": "dabid",
  "email": "david@hotmail",
  "phoneNumber": "052-783-0987",
  "address": "jerudalem, har hotzvim, 346",
  "permission": "customer"
}

# User
# ADD Payment Info
POST http://localhost:8080/api/users/:userId/pay
Content-Type: application/json

{
  "creditNum": "...",
  "cvv": "---",
  "expDate": "..."
}

# Product
# POST New Product
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "productName": "...",
  "description": "...",
  "typeId": "...",
  "cost": "...",
  "brand": "..."
}

# POST New Item
POST http://localhost:8080/api/products/:productId
Content-Type: application/json

{
  "color": "...",
  "amount": "..."
}

# Orders
# POST New Order
POST http://localhost:8080/api/orders/neworder/:userId

# ADD Item To Order
POST http://localhost:8080/api/orders/:orderId/items
Content-Type: application/json

{
  "itemId": "...",
  "amount": "..."
}

# ADD Photo To Product
POST http://localhost:8080/api/items/:itemId/photos
Content-Type: image/jpeg, image/png

# PUT
# User
# CHANGE Active Payment
PUT http://localhost:8080/api/users/:userId/activepay
Content-Type: application/json

"paymentInfoId"

# Product
# EDIT Item
# EDIT Product

# Orders
# PUT Fulfill Order
PUT http://localhost:8080/api/orders/:orderId
Content-Type: application/json

{
  "totalCost": "...",
  "paymentInfoId": "...",
  "orderId": "..."
}

